"""
Loads monthly telescope stats from csv files generated by get_vimg_stats.py
Each file is a monthly summary of telescope stats

Adapted by Claude Sonnet 4.6 from IQ_stats_plot.py
"""
import sys
import os
import glob
import pyLAST as pla
import pandas as pd
import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt

# --- Constants ---
FIGSIZE = (20, 8)
FONT_SIZE_LABEL = 14
FONT_SIZE_TICK_X = 10
FONT_SIZE_TICK_Y = 12
PROPERTY_LABEL = "FWHM"
PROPERTY_UNIT = "arcsec"

REQUIRED_COLUMNS = {"tel_labels", "telmean", "telstd"}


def series_label_from_filename(filepath: str) -> str:
    """Extract a series label from the first two underscore-separated parts of the filename.

    E.g. 'site1_night2_stats.csv' -> 'site1_night2'
    """
    stem = os.path.splitext(os.path.basename(filepath))[0]
    parts = stem.split("_")
    return "_".join(parts[:2])


def load_csv_files(folder: str) -> tuple[list[pd.DataFrame], list[str]]:
    """Load all CSV files from the given folder into a list of DataFrames.

    Returns a tuple of (dataframes, series_labels) where each label is derived
    from the first two underscore-separated parts of the corresponding filename.
    """
    csv_files = glob.glob(os.path.join(folder, "*.csv"))
    if not csv_files:
        print(f"No CSV files found in: {folder}")
        sys.exit(1)

    dataframes = []
    series_labels = []
    for csv_file in csv_files:
        try:
            df = pd.read_csv(csv_file)
            missing = REQUIRED_COLUMNS - set(df.columns)
            if missing:
                print(f"Warning: Skipping '{csv_file}' - missing columns: {missing}")
                continue
            dataframes.append(df)
            series_labels.append(series_label_from_filename(csv_file))
        except Exception as e:
            print(f"Warning: Could not read '{csv_file}': {e}")

    if not dataframes:
        print("No valid CSV files could be loaded. Exiting.")
        sys.exit(1)

    return dataframes, series_labels


def plot_telstat(dataframes: list[pd.DataFrame], series_labels: list[str], output_folder: str) -> None:
    """Plot telescope statistics as a grouped bar chart with error bars.

    Bars from each dataframe are placed side by side, centered on each tel_label.
    Series labels are derived from the source CSV filenames.
    The plot is saved as a PNG in output_folder.
    """
    fig, ax = plt.subplots(figsize=FIGSIZE)

    n_groups = len(dataframes)
    bar_width = 0.8 / n_groups  # total group width = 0.8, divided evenly
    # Offsets so bars are centered: e.g. for 3 groups -> -0.267, 0, +0.267
    offsets = [(i - (n_groups - 1) / 2) * bar_width for i in range(n_groups)]

    # Use the tel_labels from the first dataframe as the x-axis positions
    base_labels = dataframes[0]["tel_labels"].astype(str).tolist()
    x = range(len(base_labels))

    for index, (df, label) in enumerate(zip(dataframes, series_labels)):
        means = df["telmean"].values
        stds = df["telstd"].values
        x_positions = [pos + offsets[index] for pos in x]

        ax.bar(
            x_positions,
            means,
            width=bar_width,
            color=pla.TABCOLORS[index],
            label=label,
        )
        ax.errorbar(
            x_positions,
            means,
            yerr=stds,
            fmt="none",
            capsize=4,
            color="black",
        )

    ax.set_xticks(list(x))
    ax.set_xticklabels(base_labels)
    ax.legend(fontsize=FONT_SIZE_TICK_Y)
    ax.grid(axis="y")
    ax.tick_params(axis="x", labelsize=FONT_SIZE_TICK_X)
    ax.tick_params(axis="y", labelsize=FONT_SIZE_TICK_Y)
    ax.set_ylabel(f"{PROPERTY_LABEL} ({PROPERTY_UNIT})", fontsize=FONT_SIZE_LABEL)
    ax.set_xlabel("Telescope Label", fontsize=FONT_SIZE_LABEL)
    ax.set_title(f"{PROPERTY_LABEL} Telescope Statistics", fontsize=FONT_SIZE_LABEL + 4)

    plt.tight_layout()

    output_path = os.path.join(output_folder, f"{PROPERTY_LABEL}_telescope_stats.png")
    plt.savefig(output_path, dpi=150)
    print(f"Plot saved to: {output_path}")

    plt.show()


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python plot_telstat.py <csv_folder>")
        sys.exit(1)

    csv_folder = sys.argv[1]

    if not os.path.isdir(csv_folder):
        print(f"Error: '{csv_folder}' is not a valid directory.")
        sys.exit(1)

    dataframes, series_labels = load_csv_files(csv_folder)
    plot_telstat(dataframes, series_labels, csv_folder)
    print("Finished.")


if __name__ == "__main__":
    main()